#!/usr/bin/env python3
"""Plot cell-cycle ODE marker trajectories exported by RuleParser audit CSV."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path


MARKERS = [
    ("p21", ["state_p21", "intracellular_CellCycleArrest_p21"], "p21"),
    ("Cd", ["state_cyclin_d", "intracellular_CellCycleArrest_Cd"], "Cd"),
    ("E2Fa", ["state_e2f_activity", "intracellular_CellCycleArrest_E2Fa"], "E2F_a"),
    ("Ce", ["state_cyclin_e", "intracellular_CellCycleArrest_Ce"], "Ce"),
    ("Ca", ["state_cyclin_a", "intracellular_CellCycleArrest_Ca"], "Ca"),
    ("Cb", ["state_cyclin_b", "intracellular_CellCycleArrest_Cb"], "Cb"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a six-panel SVG plot for the CellCycleArrest Antimony ODE time series."
    )
    parser.add_argument(
        "--input",
        default="Rules_project/simulation_time_series/global_simulation_history.csv",
        help="Audit CSV generated by RuleParser.",
    )
    parser.add_argument("--output", default=None, help="Output SVG path.")
    parser.add_argument("--cell-id", type=int, default=1, help="Cell_ID to plot.")
    parser.add_argument(
        "--mcs-per-cycle",
        type=float,
        default=1000.0,
        help="MCS units per normalized cell cycle. Current CellCycle project uses 1000 MCS/cycle.",
    )
    parser.add_argument("--max-cycles", type=float, default=4.0, help="Maximum x-axis value in cell cycles.")
    parser.add_argument("--title", default="Cell-cycle regulatory ODE model", help="SVG title.")
    return parser.parse_args()


def read_rows(path: Path, cell_id: int, mcs_per_cycle: float, max_cycles: float) -> tuple[list[dict], list[str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        fieldnames = list(reader.fieldnames or [])
        rows = []
        for row in reader:
            try:
                row_cell_id = int(float(row.get("Cell_ID", "")))
                mcs = float(row.get("MCS", ""))
            except ValueError:
                continue
            if row_cell_id != cell_id:
                continue
            cycle = mcs / mcs_per_cycle if mcs_per_cycle else mcs
            if cycle > max_cycles:
                continue
            row["_cycle"] = cycle
            rows.append(row)
    rows.sort(key=lambda item: item["_cycle"])
    return rows, fieldnames


def marker_series(rows: list[dict], columns: list[str]) -> tuple[list[float], list[float], str | None]:
    for column in columns:
        values = []
        xs = []
        for row in rows:
            raw = row.get(column)
            if raw in (None, ""):
                continue
            try:
                value = float(raw)
            except ValueError:
                continue
            if math.isfinite(value):
                xs.append(float(row["_cycle"]))
                values.append(value)
        if values:
            return xs, values, column
    return [], [], None


def nice_range(values: list[float]) -> tuple[float, float]:
    if not values:
        return 0.0, 1.0
    lower = min(values)
    upper = max(values)
    if lower == upper:
        pad = abs(lower) * 0.1 or 0.1
    else:
        pad = (upper - lower) * 0.12
    lower -= pad
    upper += pad
    if lower >= 0:
        lower = max(0.0, lower)
    return lower, upper


def points_to_path(xs: list[float], ys: list[float], x0: float, y0: float, w: float, h: float, xmax: float) -> str:
    ymin, ymax = nice_range(ys)
    if ymax == ymin:
        ymax = ymin + 1.0
    commands = []
    for x, y in zip(xs, ys):
        px = x0 + (x / xmax) * w if xmax else x0
        py = y0 + h - ((y - ymin) / (ymax - ymin)) * h
        commands.append(("M" if not commands else "L") + f"{px:.2f},{py:.2f}")
    return " ".join(commands)


def tick_labels(ymin: float, ymax: float) -> list[float]:
    return [ymin, (ymin + ymax) / 2.0, ymax]


def svg_escape(text: object) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render_svg(rows: list[dict], output: Path, title: str, max_cycles: float) -> None:
    panel_w = 360
    panel_h = 160
    plot_w = 270
    plot_h = 105
    left_margin = 64
    top_margin = 36
    col_gap = 54
    row_gap = 70
    width = 2 * panel_w + col_gap + 70
    height = 3 * panel_h + 2 * row_gap + 90
    letters = "ABCDEF"

    chunks = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        "<style>",
        "text{font-family:Arial,Helvetica,sans-serif;fill:#111}",
        ".label{font-size:18px}.axis{font-size:13px}.letter{font-size:28px;font-weight:700}",
        ".title{font-size:22px;font-weight:700}.line{fill:none;stroke:#111;stroke-width:2.2}",
        ".grid{stroke:#e5e7eb;stroke-width:1}.axis-line{stroke:#111;stroke-width:1.2}",
        "</style>",
        f'<text x="38" y="32" class="title">{svg_escape(title)}</text>',
    ]

    for index, (name, columns, ylabel) in enumerate(MARKERS):
        row_idx = index // 2
        col_idx = index % 2
        panel_x = 34 + col_idx * (panel_w + col_gap)
        panel_y = 56 + row_idx * (panel_h + row_gap)
        plot_x = panel_x + left_margin
        plot_y = panel_y + top_margin
        xs, ys, used_column = marker_series(rows, columns)
        ymin, ymax = nice_range(ys)

        chunks.append(f'<text x="{panel_x}" y="{panel_y + 24}" class="letter">{letters[index]}</text>')
        chunks.append(
            f'<text x="{plot_x - 42}" y="{plot_y + plot_h / 2}" class="label" '
            f'transform="rotate(-90 {plot_x - 42},{plot_y + plot_h / 2})">{svg_escape(ylabel)}</text>'
        )
        chunks.append(f'<rect x="{plot_x}" y="{plot_y}" width="{plot_w}" height="{plot_h}" fill="white"/>')
        for frac in (0.0, 0.5, 1.0):
            gy = plot_y + frac * plot_h
            chunks.append(f'<line x1="{plot_x}" y1="{gy:.2f}" x2="{plot_x + plot_w}" y2="{gy:.2f}" class="grid"/>')
        chunks.append(f'<rect x="{plot_x}" y="{plot_y}" width="{plot_w}" height="{plot_h}" fill="none" class="axis-line"/>')

        if xs and ys:
            path = points_to_path(xs, ys, plot_x, plot_y, plot_w, plot_h, max_cycles)
            chunks.append(f'<path d="{path}" class="line"/>')
            for x, y in zip(xs[:: max(1, len(xs) // 35)], ys[:: max(1, len(ys) // 35)]):
                px = plot_x + (x / max_cycles) * plot_w if max_cycles else plot_x
                py = plot_y + plot_h - ((y - ymin) / (ymax - ymin)) * plot_h if ymax != ymin else plot_y + plot_h / 2
                chunks.append(f'<circle cx="{px:.2f}" cy="{py:.2f}" r="2.5" fill="#0072b2"/>')
        else:
            chunks.append(
                f'<text x="{plot_x + 14}" y="{plot_y + 58}" class="axis">No data column found for {svg_escape(name)}</text>'
            )

        for tick in range(5):
            tx = plot_x + (tick / 4.0) * plot_w
            value = (tick / 4.0) * max_cycles
            chunks.append(f'<line x1="{tx:.2f}" y1="{plot_y + plot_h}" x2="{tx:.2f}" y2="{plot_y + plot_h + 5}" class="axis-line"/>')
            chunks.append(f'<text x="{tx - 5:.2f}" y="{plot_y + plot_h + 21}" class="axis">{value:g}</text>')
        for value in tick_labels(ymin, ymax):
            py = plot_y + plot_h - ((value - ymin) / (ymax - ymin)) * plot_h if ymax != ymin else plot_y + plot_h / 2
            chunks.append(f'<text x="{plot_x - 42}" y="{py + 4:.2f}" class="axis">{value:.3g}</text>')

        if row_idx == 2:
            chunks.append(
                f'<text x="{plot_x + 70}" y="{plot_y + plot_h + 46}" class="label">Number of Cell Cycles</text>'
            )
        if used_column:
            chunks.append(f'<text x="{plot_x}" y="{plot_y - 10}" class="axis">{svg_escape(used_column)}</text>')

    chunks.append("</svg>")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(chunks), encoding="utf-8")


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        raise SystemExit(f"Input CSV does not exist: {input_path}")
    output = Path(args.output) if args.output else input_path.parent / "cell_cycle_ode_timeseries.svg"
    rows, _fieldnames = read_rows(input_path, args.cell_id, args.mcs_per_cycle, args.max_cycles)
    if not rows:
        raise SystemExit(f"No rows for Cell_ID={args.cell_id} in {input_path}")
    render_svg(rows, output, args.title, args.max_cycles)
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
